-- Give the built-in "/contact" page a real menu title, so the public navigation
-- can be fully CMS-driven without the Contact link disappearing (#2818,
-- owner decision 5).
--
-- WHAT CHANGED ABOVE THIS MIGRATION. `src/components/website-header.tsx` used to
-- append a hard-coded { href: "/contact", label: "Contact" } entry after the
-- CMS-driven links. That is the right thing to delete — the nav belongs to the
-- club, not to the code — but the contact row has always seeded menuTitle = '',
-- so deleting it alone would silently remove the Contact link from every
-- deployment that had never edited that field. This migration ships the data the
-- deletion assumes.
--
-- VALUE-SCOPED, which is the whole safety property. The WHERE matches only rows
-- whose menuTitle is still EXACTLY the seeded empty string, so:
--   * a club that already typed its own label ("Contact Us", "Get in touch",
--     "Kōrero mai") keeps it, byte for byte;
--   * a club that deliberately blanked the field to hide the page from the menu
--     is indistinguishable from one that never touched it — and gets the link
--     back. That is accepted rather than hidden: the empty string is the seeded
--     default, there is no stored record of intent to tell the two apart, and
--     restoring a link a site has always shown is the safer of the two errors.
--     A club that wants it hidden clears the field again in one edit.
--
-- IDEMPOTENT: the value written ('Contact') is not the value matched (''), so a
-- second run matches nothing. Re-runnable, which is what lets the verification
-- fixture assert idempotentReRun.
--
-- "updatedAt" is deliberately NOT touched. This is a system repair of a seeded
-- default, not an admin edit, and the column is what the admin UI shows as "last
-- edited" — the same treatment 20260802110000 (#2484) and 20260802140000 (#2490)
-- chose, and it keeps the session-clock DML gate (#1627) silent because there is
-- no CURRENT_TIMESTAMP/now() in the payload.
--
-- OLD-COLOUR COMPATIBLE IN BOTH DIRECTIONS: no schema change, so a draining old
-- colour's compiled queries are unaffected. It read menuTitle already and simply
-- starts seeing a non-empty one, which adds a nav link it also rendered (from its
-- own hard-coded entry) — so during the drain the old colour shows Contact once,
-- from its static list, and the new colour shows it once, from this row. Rolling
-- back restores the static entry and leaves this value in place, which is a
-- duplicate-free nav either way.
--
-- Keep the value in sync with starterPageContent in
-- prisma/starter-page-content.ts (enforced by
-- src/lib/__tests__/page-content-starter-backfill.test.ts).
UPDATE "PageContent"
SET "menuTitle" = 'Contact'
WHERE "slug" = 'contact'
  AND "menuTitle" = '';
