-- Legacy structure contraction, Release B — #2129 step 2: drop the frozen
-- member/non-member boolean-keyed hut-rate table "SeasonRate".
--
-- Background. The E4 pricing re-key (#1930,
-- 20260717140000_pricing_rekey_by_membership_type) moved authoritative nightly
-- pricing onto "MembershipTypeSeasonRate" (season x membership type x optional
-- age tier) and fanned every existing SeasonRate row forward, but deliberately
-- RETAINED SeasonRate as a rollback net. E13 (#1939,
-- 20260720120000_contract_drop_entrance_fee_and_agetier_xero_group) could not
-- drop it because the live public {{hut-fees}} page-content embed
-- (loadPublicHutFees) still read its member/non-member split.
--
-- Why this is old-code compatible now. #2129 step 1 (Release A) re-sourced that
-- embed onto MembershipTypeSeasonRate and removed the admin season routes'
-- unused `rates` include, eliminating the last APPLICATION-RUNTIME reader. The
-- only survivors were seed-time reader/writers outside src/ — the
-- `include: { rates: true }` and `rates: { create: ... }` in
-- e2e/setup/seed-second-lodge.ts and `createMissingSeasonRates` in
-- prisma/seed.ts — and the SAME pull request as this migration removes all
-- three. Seeders are not the deployed web runtime, so no draining old colour
-- issues SQL naming "SeasonRate". This migration is therefore legal ONLY once
-- the #2129 step 1 release is the deployed/draining colour in production; do
-- not run it before that release has shipped and soaked.
--
-- No data is lost that any code can still resolve: every SeasonRate row was
-- copied forward by the E4 fan-out backfill (isMember=true -> every
-- MEMBER_RATE membership type, isMember=false -> the built-in NON_MEMBER type)
-- and pricing has resolved from MembershipTypeSeasonRate since.
--
-- Lock impact: DROP TABLE takes a brief ACCESS EXCLUSIVE lock on one cold
-- config table (SeasonRate is not in HOT_TABLE_SQL_REGEX). Its FK to Season is
-- ON DELETE CASCADE and no other table references it, so no dependent object
-- survives the drop. No table rewrite, no row scan, no DML, no session clock,
-- no provider call.

-- 1. Retired member/non-member boolean-keyed hut-rate table (E4 #1930
--    superseded it with MembershipTypeSeasonRate; #2129 removed its readers).
DROP TABLE "SeasonRate";
