/**
 * Rendered-email equivalence gate (#2689).
 *
 * The #2689 split moved every template out of a 5,000-line monolith into one
 * module per message family. Inline email CSS is order-dependent, so a move
 * that reads as mechanical in the diff can still change the cascade a mail
 * client applies. The owner's rule for that split is that rendered output stays
 * byte-for-byte invariant and that ANY diff is a blocking finding, so this test
 * pins the complete rendered body of every template — not a fragment, not a
 * function name — against committed hashes.
 *
 * It is a permanent gate, not a one-off proof: the next structural move must
 * not be able to change output silently either.
 *
 * WHEN IT FAILS. Dump both sides and diff them:
 *
 *   EMAIL_RENDER_DUMP=/tmp/before git stash && npx vitest run src/lib/__tests__/email-render-equivalence.test.ts
 *   EMAIL_RENDER_DUMP=/tmp/after  git stash pop && npx vitest run src/lib/__tests__/email-render-equivalence.test.ts
 *   diff -r /tmp/before /tmp/after
 *
 * If — and only if — the change to the output is intended and reviewed, rewrite
 * the pins with UPDATE_EMAIL_RENDER_PINS=1. That mode always fails the run, so
 * a regenerated pin file can never be mistaken for a passing gate.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";

// The palette is read per render from the club (Site Style) theme and IS part
// of the output. Pin it to the site default — the same values a cold cache
// already uses — so the corpus is deterministic and never reaches the database.
vi.mock("@/lib/club-theme", () => ({
  getWebsiteThemeRenderState: async () => {
    const { DEFAULT_CLUB_THEME_VALUES } = await import("@/lib/club-theme-schema");
    return { values: DEFAULT_CLUB_THEME_VALUES, css: "" };
  },
}));

import { EMAIL_TEMPLATE_DEFINITIONS } from "@/lib/email-message-registry";
import {
  EMAIL_RENDER_CASES,
  type EmailRenderCase,
} from "@/lib/__tests__/support/email-render-cases";
import {
  EMAIL_TEMPLATE_MODULE_EXPORTS,
  REGISTRY_KEY_RENDERERS,
  REGISTRY_KEYS_WITHOUT_A_TEMPLATE_FUNCTION,
} from "@/lib/__tests__/support/email-render-coverage";

const PINS_PATH = path.join(
  __dirname,
  "support",
  "email-render-pins.txt",
);

const PINS_HEADER = [
  "# Rendered-email pins (#2689). One line per case: <id> <TAB> <bytes> <TAB> sha256.",
  "# Generated by src/lib/__tests__/email-render-equivalence.test.ts.",
  "# Regenerate ONLY for a reviewed, intended output change:",
  "#   UPDATE_EMAIL_RENDER_PINS=1 npx vitest run src/lib/__tests__/email-render-equivalence.test.ts",
].join("\n");

function digest(body: string): { bytes: number; sha256: string } {
  const buffer = Buffer.from(body, "utf8");
  return {
    bytes: buffer.byteLength,
    sha256: createHash("sha256").update(buffer).digest("hex"),
  };
}

function renderAll(): Map<string, { bytes: number; sha256: string }> {
  const rendered = new Map<string, { bytes: number; sha256: string }>();
  const dumpDir = process.env.EMAIL_RENDER_DUMP;
  if (dumpDir) mkdirSync(dumpDir, { recursive: true });

  for (const testCase of EMAIL_RENDER_CASES) {
    const body = testCase.render();
    if (dumpDir) {
      writeFileSync(
        path.join(dumpDir, `${testCase.id.replace(/[^A-Za-z0-9_.-]/g, "_")}.txt`),
        body,
        "utf8",
      );
    }
    rendered.set(testCase.id, digest(body));
  }
  return rendered;
}

function readPins(): Map<string, { bytes: number; sha256: string }> {
  const raw = readFileSync(PINS_PATH, "utf8");
  const pins = new Map<string, { bytes: number; sha256: string }>();
  for (const line of raw.split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const [id, bytes, sha256] = line.split("\t");
    if (!id || !bytes || !sha256) {
      throw new Error(`Malformed pin line in email-render-pins.txt: ${line}`);
    }
    pins.set(id, { bytes: Number(bytes), sha256 });
  }
  return pins;
}

function writePins(rendered: Map<string, { bytes: number; sha256: string }>) {
  const lines = [...rendered.entries()].map(
    ([id, { bytes, sha256 }]) => `${id}\t${bytes}\t${sha256}`,
  );
  writeFileSync(PINS_PATH, `${PINS_HEADER}\n${lines.join("\n")}\n`, "utf8");
}

describe("rendered-email equivalence (#2689)", () => {
  const rendered = renderAll();

  if (process.env.UPDATE_EMAIL_RENDER_PINS === "1") {
    it("regenerated the pins and therefore FAILS this run", () => {
      writePins(rendered);
      throw new Error(
        `Rewrote ${PINS_PATH} with ${rendered.size} pins. This mode always fails: ` +
          "review the diff, confirm the output change was intended, then re-run without " +
          "UPDATE_EMAIL_RENDER_PINS.",
      );
    });
    return;
  }

  it("has a committed pin file", () => {
    expect(
      existsSync(PINS_PATH),
      `${PINS_PATH} is missing. Without it this gate proves nothing.`,
    ).toBe(true);
  });

  it("pins exactly the cases that exist — no case silently added or dropped", () => {
    const pins = readPins();
    const renderedIds = [...rendered.keys()].sort();
    const pinnedIds = [...pins.keys()].sort();
    expect(pinnedIds).toEqual(renderedIds);
  });

  it("renders every template byte-for-byte identically to its pin", () => {
    const pins = readPins();
    const drifted: string[] = [];
    for (const [id, actual] of rendered) {
      const pinned = pins.get(id);
      if (!pinned) continue; // covered by the id-set test above
      if (pinned.sha256 !== actual.sha256 || pinned.bytes !== actual.bytes) {
        drifted.push(
          `${id}: pinned ${pinned.bytes}B ${pinned.sha256.slice(0, 12)} -> rendered ` +
            `${actual.bytes}B ${actual.sha256.slice(0, 12)}`,
        );
      }
    }
    expect(
      drifted,
      "Rendered email output changed. Under #2689 this is a BLOCKING finding, not an " +
        "expectation to update. Re-read the module docblock for how to dump and diff " +
        "the bodies:\n" +
        drifted.join("\n"),
    ).toEqual([]);
  });

  it("covers every exported render function in every template module", () => {
    const coveredFns = new Set(EMAIL_RENDER_CASES.map((c: EmailRenderCase) => c.fn));
    const uncovered: string[] = [];
    for (const [moduleName, exportNames] of Object.entries(
      EMAIL_TEMPLATE_MODULE_EXPORTS,
    )) {
      for (const exportName of exportNames) {
        if (!coveredFns.has(exportName)) uncovered.push(`${moduleName}.${exportName}`);
      }
    }
    expect(
      uncovered,
      "These exported render functions have no case in email-render-cases.ts, so a " +
        "structural move could change their output unnoticed:\n" + uncovered.join("\n"),
    ).toEqual([]);
  });

  it("covers every production template the message registry registers", () => {
    const coveredFns = new Set(EMAIL_RENDER_CASES.map((c: EmailRenderCase) => c.fn));
    const unmapped: string[] = [];
    const uncovered: string[] = [];
    for (const definition of EMAIL_TEMPLATE_DEFINITIONS) {
      if (REGISTRY_KEYS_WITHOUT_A_TEMPLATE_FUNCTION.has(definition.key)) continue;
      const renderer = REGISTRY_KEY_RENDERERS[definition.key];
      if (!renderer) {
        unmapped.push(definition.key);
        continue;
      }
      if (!coveredFns.has(renderer)) uncovered.push(`${definition.key} -> ${renderer}`);
    }
    expect(
      unmapped,
      "Registry template keys with no mapped render function. Add the mapping in " +
        "email-render-coverage.ts (or record why the key has no template function):\n" +
        unmapped.join("\n"),
    ).toEqual([]);
    expect(
      uncovered,
      "Registry template keys whose render function has no render case:\n" +
        uncovered.join("\n"),
    ).toEqual([]);
  });

  it("renders deterministically — the same case twice produces the same bytes", () => {
    const second = renderAll();
    for (const [id, first] of rendered) {
      expect(second.get(id), `${id} rendered differently on a second call`).toEqual(
        first,
      );
    }
  });
});
